name: Validate Deployment and Email Results

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  validate-deployment-and-send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: develop  # Checkout the develop branch
          fetch-depth: 0  # Fetch the entire history to ensure we are working with the latest code

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir -p ~/cli/sf
          tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
          echo "$HOME/cli/sf/bin" >> $GITHUB_PATH
          ~/cli/sf/bin/sf version

      - name: Authenticate to QA Org
        run: |
          echo "${{ secrets.SFDX_QA_URL }}" > ./SFDX_QA_URL.txt
          sf org login sfdx-url --sfdx-url-file ./SFDX_QA_URL.txt --set-default --alias qa

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Run Deployment Dry-Run
        id: deploy
        run: |
          FILE_NAME="deployment_results_${{ env.date }}.txt"
          echo "Using file name: $FILE_NAME"
          sf project deploy start --source-dir "force-app" --target-org qa --dry-run --json > "$FILE_NAME"
          echo "Deployment results saved to: $FILE_NAME"

      - name: Upload Deployment Results
        uses: actions/upload-artifact@v3
        with:
          name: deployment-results
          path: deployment_results_*.txt

      - name: Send Deployment Results via Gmail
        if: always()  # Ensures this step runs regardless of success or failure of the deployment
        uses: dawidd6/action-send-mail@v4
        with:
          connection_url: smtp+starttls://{{ secrets.EMAIL_USERNAME }}:{{ secrets.EMAIL_PASSWORD }}@smtp.gmail.com:587
          subject: Deployment Results for Develop Branch
          to: harsh@crmlanding.in  # Replace with the actual recipient email(s)
          from: "GitHub Actions <{{ secrets.EMAIL_USERNAME }}>"
          body: |
            Hello,

            Please find attached the deployment results from the latest workflow run for the develop branch.

            Regards,
            GitHub Actions
          attachments: deployment_results_*.txt
