name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      From Branch:
        description: "Enter From Branch Name"
        default: "From Branch"
      commit_id:
        description: "Please enter commit id"
        default: "commit id"
      To Branch:
        description: "Enter To Branch Name"
        default: "To Branch"

jobs:
  Deploying-Specified-Commits:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
        - uses: actions/setup-node@v3
          with:
            node-version: '20'

        - name: 'Install Salesforce CLI'
          run: |
                npm install @salesforce/cli --global
                
        - name: 'Display input commit ID'
          run: echo "Hello ${{ github.event.inputs.name }}"

        - name: 'Display salesforce cli version'
          run: echo "Cli Version ${{sfdx --version}}"
