name: Validate Deployment Dry-Run

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  validate-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: develop  # Checkout the develop branch
          fetch-depth: 0  # Fetch the entire history to ensure we are working with the latest code

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf version

      - name: Authenticate to QA Org
        run: |
          echo "${{ secrets.SFDX_QA_URL }}" > ./SFDX_QA_URL.txt
          sf org login sfdx-url --sfdx-url-file ./SFDX_QA_URL.txt --set-default --alias qa

      - name: Run Deployment Dry-Run
        run: |
          echo "Starting deployment dry-run..."
          sf project deploy start --source-dir "force-app" --target-org qa --dry-run
