name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      From Branch:
        description: "Enter From Branch Name"
        default: "From Branch"
      commit_id:
        description: "Please enter commit id"
        default: "commit id"
      To Branch:
        description: "Enter To Branch Name"
        default: "To Branch"

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Display input commit ID
        run: echo "Hello ${{ github.event.inputs.name }}"
